name: Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --dev
        uv add mkdocs mkdocs-material mkdocs-mermaid2-plugin

    - name: Test documentation build
      run: |
        # Test if documentation files exist and are valid
        if [ -f "mkdocs.yml" ]; then
          mkdocs build --strict
        fi
        if [ -f "docs/PROJECT_DOCUMENTATION.md" ]; then
          echo "Project documentation exists"
        fi
        if [ -f "docs/API_REFERENCE.md" ]; then
          echo "API reference documentation exists"
        fi

  check-links:
    name: Check Documentation Links
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --dev
        uv add lychee-linkchecker

    - name: Check links
      run: |
        lychee docs/ --verbose --no-progress --exclude-mail --exclude "localhost" --timeout 30